# Generated by Django 3.1.14 on 2024-12-20 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='username',
            field=models.ForeignKey(default='none', limit_choices_to={'role__ne': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, to='main.user', to_field='username'),
            preserve_default=False,
        ),
    ]
